item_mapping_dict = {
    "Obstetrics and Gynecology Consultation": "Obstetrics and Gynecology Consultation",
    "PEDIA Consult": "Pediatrics Consultation",
    "PCV": "PCV Vaccine",
    "6 IN 1": "6 IN 1 Vaccine",
    "ROTATEQ": "Rotateq Vaccine",
    "FLU VACCINE": "Flu Vaccine",
    "ROTARIX": "Rotarix Vaccine",
    "Surgery Procedure (8500)": "Surgery Procedure (8500)",
    "PACKAGES": "Medical Packages",
    "MMR": "MMR Vaccine",
    "SWAB": "Swab Test",
    "MENINGO": "Meningococcal Vaccine",
    "TD": "TD Vaccine",
    "JAP ENCEPH": "Japanese Encephalitis Vaccine",
    "MICROBIOLOGY": "Clinical Microbiology",
    "GENERAL ULTRASOUND": "General Ultrasound",
    "Urologist Consult": "Urology Consultation",
    "VARICELLA": "Varicella Vaccine",
    "MMRV": "MMRV Vaccine",
    "MEDICAL CERTIFICATE": "Medical Certificate",
    "TT": "Tetanus Toxoid Vaccine",
    "Family Planning": "Family Planning",
    "HEMATOLOGY": "Hematology",
    "IM": "Intramuscular Injection",
    "HEPA A": "Hepatitis A Vaccine",
    "OTHERS": "Miscellaneous",
    "Laser Circumcision": "Laser Circumcision",
    "GARDASIL 4": "Gardasil 4 Vaccine",
    "IMPLANT INSERTION": "Implant Insertion",
    "IMPLANT REMOVAL": "Implant Removal",
    "MED CLEARANCE": "Medical Clearance",
    "TYPHOID": "Typhoid Vaccine",
    "Pro Biolyte (Banana)": "Pro Biolyte (Banana)",
    "Regular Circumcision": "Regular Circumcision",
    "OPV": "Oral Polio Vaccine (OPV)",
    "IPV": "Inactivated Polio Vaccine (IPV)",
    "Nasatapp Drops": "Nasatapp Drops",
    "Nasatapp Syrup": "Nasatapp Syrup",
    "Ceelin Drops 30ml": "Ceelin Drops 30ml",
    "Zinc Sulfate (E-Zinc) 15ml": "Zinc Sulfate (E-Zinc) 15ml",
    "Hydrite": "Hydrite",
    "BCG": "BCG Vaccine",
    "PPD": "PPD Test",
    "MEDICINE": "Medicine",
    "Surgery Consult": "Surgery Consultation",
    "Surgery Procedure (10,500)": "Surgery Procedure (10500)"
}
