item_mapping_dict = {
    "OBSTETRICS and GYNECOLOGY": "Obstetrics and Gynecology Consultation",
    "PEDIA Consult": "Pediatrics Consultation",
    "Obstetrics and Gynecology Consultation": "Obstetrics and Gynecology",
    "PCV": "PCV Vaccine",
    "6 IN 1": "6 IN 1 Vaccine",
    "ROTATEQ": "Rotateq Vaccine",
    "FLU VACCINE": "Flu Vaccine",
    "ROTARIX": "Rotarix Vaccine",
    "Surgery Procedure (8500)": "Surgery Procedure (8500)",
    "Surgery Procedure (9500)": "Surgery Procedure (9500)",
    "Surgery Procedure (17,000)": "Surgery Procedure (17000)",
    "PACKAGES": "Medical Packages",
    "Packages" : "Medical Packages",
    "REI": "REI",
    "MMR": "MMR Vaccine",
    "SWAB": "Swab Test",
    "MENINGO": "Meningococcal Vaccine",
    "Surgery Procedure (10,500)": "Surgery Procedure (10500)",
    "TD": "TD Vaccine",
    "JAP ENCEPH": "Japanese Encephalitis Vaccine",
    "MICROBIOLOGY": "Clinical Microbiology",
    "GENERAL ULTRASOUND": "General Ultrasound",
    "Urologist Consult": "Urology Consultation",
    "Cardio": "Cardiology Consultation",
    "VARICELLA": "Varicella Vaccine",
    "MMRV": "MMRV Vaccine",
    "MEDICAL CERTIFICATE": "Medical Certificate",
    "Medical Certificate": "Medical Certificate",
    "Surgery Procedure (11,500)": "Surgery Procedure (11500)",
    "Surgery Consult": "Surgery Consultation",
    "TT": "Tetanus Toxoid Vaccine",
    "FAMILY PLANNING": "Family Planning",
    "Surgery Procedure (4500)": "Surgery Procedure (4500)",
    "HEMATOLOGY": "Hematology",
    "IM": "Intramuscular Injection",
    "HEPA A": "Hepatitis A Vaccine",
    "OTHERS": "Miscellaneous",
    "Surgery Procedure (6500)": "Surgery Procedure (6500)",
    "Laser Circumcision": "Laser Circumcision",
    "GARDASIL 4": "Gardasil 4 Vaccine",
    "IMPLANT INSERTION": "Implant Insertion",
    "IMPLANT REMOVAL": "Implant Removal",
    "MED CLEARANCE": "Medical Clearance",
    "TYPHOID": "Typhoid Vaccine",
    "Pro Biolyte (Banana)": "Pro Biolyte (Banana)",
    "Regular Circumcision": "Regular Circumcision",
    "Surgery Procedure (3500)": "Surgery Procedure (3500)",
    "OPV": "Oral Polio Vaccine (OPV)",
    "IPV": "Inactivated Polio Vaccine (IPV)",
    "Nasatapp Drops": "Nasatapp Drops",
    "Nasatapp Syrup": "Nasatapp Syrup",
    "Ceelin Drops 30ml": "Ceelin Drops 30ml",
    "Zinc Sulfate (E-Zinc) 15ml": "Zinc Sulfate (E-Zinc) 15ml",
    "Hydrite": "Hydrite",
    "BCG": "BCG Vaccine",
    "PPD": "PPD Test",
    "CLINICAL CHEMISTRY": "Clinical Chemistry",
    "CLINICAL MICROSCOPY": "Clinical Microscopy",
    "Surgery Procedure (7500)": "Surgery Procedure (7500)",
    "Endocrinologist Consult": "Endocrinologist Consultation",
    "HEPA B IG": "Hepatitis B Immune Globulin Vaccine",
    "Ear Piercing": "Ear Piercing",
    "CHANGE OF DRESSING": "Change of Dressing",
    "IUD removal": "Intrauterine Device Removal",
    "IUD insertion": "Intrauterine Device Insertion",
    "Surgery Procedure (2500)": "Surgery Procedure (2500)",
    "Surgery Procedure (1500)": "Surgery Procedure (1500)",
    "Cetirizine Drops Allerkid Drops": "Cetirizine (Allerkid Drops)",
    "Admin Fee": "Administration Fee",
    "Paracetamol Drops Biogesic Drops": "Paracetamol Drops (Biogesic Drops)",
    "Zinc Oxide + Calamine (Saphclamine)": "Zinc Oxide and Calamine (Saphclamine)",
    "Cetirizine Syrup Allerkid Syrup": "Cetirizine (Allerkid Syrup)",
    "NST": "Non-Stress Test",
    "Sodermix": "Sodermix",
    "Salinase Max": "Salinase Max",
    "Salinase Max \"Nasal Spray Drops\"": "Salinase Max",
    "Azithromycin (Azythrex)": "Azithromycin (Azythrex)",
    "Vivalyte": "Vivalyte",
    "Nutri 10 plus drops": "Nutri 10 plus drops",
    "Clinic Fee": "Clinical Fee",
    "Salbutamol": "Salbutamol",
    "Ceelin Syrup 120ml": "Ceelin Syrup 120ml",
    "Appebon": "Appebon",
    "Vitamin C and Zinc Ceelin Plus Syrup": "Vitamin C and Zinc Ceelin Plus Syrup",
    "Paracetamol Drops (Tempra)": "Paracetamol Drops (Tempra)",
    "GARDASIL 9": "GARDASIL 9 Vaccine",
    "HEPA B": "Hepatitis B Vaccine",
    "Cardio Clearance": "Cardiology Clearance",
    "CARDIO CLEARANCE": "Cardiology Clearance",
    "Salinase Nebule": "Salinase Nebule",
    "SKIN TEST": "Skin Test",
    "Cetirizine (Temprazine)": "Cetirizine (Temprazine)",
    "IUD Insertion": "Intrauterine Device Insertion",
    "Surgery Procedure (2000)": "Surgery Procedure (2000)",
    "Surgery procedure (2000)": "Surgery Procedure (2000)",
    "Catheter Change": "Catheter Change",
    "Amoxicillin (Himox)": "Amoxicillin (Himox)",
    "Amoxicillin \"Himox\"": "Amoxicillin (Himox)",
    "Simeticone (Restime)": "Simeticone (Restime)",
    "Provits 120 ml": "Provits 120 ml",
    "Tempra Syrup": "Paracetamol Syrup (Tempra)",
    "Surgery Procedure (5500)": "Surgery Procedure (5500)",
    "Surgery Procedure (100)": "Surgery Procedure (100)",
    "Hydroaid": "Hydroaid",
    "Iron B + Complex (Ferlin)": "Iron B and Complex (Ferlin)",
    "Cetirizine Hydrochloride (Allercon-25)": "Cetirizine (Hydrochloride Allercon-25)",
    "MEDICAL CERTIFICATE W CTC": "Medical Certificate (with Certified True Copy)",
    "Medical Certificate wo CTC": "Medical Certificate",
    "Medical Certificate w/o CTC": "Medical Certificate",
    "MEDICAL CERTIFICATE W/ CTC": "Medical Certificate (with Certified True Copy)",
    "Med Cert": "Medical Certificate",
    "Hepa B Adult": "Hepatitis B Adult Vaccine",
    "Placental Doppler": "Placental Doppler",
    "Lactitol Monohydryate (Lactomax)": "Lactitol Monohydryate (Lactomax)",
    "CTC - utz": "General Ultrasound (with Certified True Copy)",
    "Ambroxol Hydrochloride (Cofzol)": "Ambroxol Hydrochloride (Cofzol)",
    "Salinase Spray": "Salinase Spray",
    "Surgery Procedure (1000)": "Surgery Procedure (1000)",
    "Histopath Deposit": "Histopathology Deposit",
    "MEDICINE": "Medicine",
    "OBGYN Consult": "Obstetrics and Gynecology Consultation",
    "PCV \"Pneumococcal\"": "PCV \"Pneumoccoccal\" Vaccine",
    "6 IN 1 \"Hexaxim\"": "6 IN 1 \"Hexaxim\" Vaccine",
    "Surgery Procedure (9000)": "Surgery Procedure (9000)",
    "Surgery Procedure (7000)": "Surgery Procedure (7000)",
    "Surgery Procedure (4000)": "Surgery Procedure (4000)",
    "Surgery Procedure (150)": "Surgery Procedure (150)",
    "Cetirizine Dihydrochloride (Trizin 5)": "Cetirizine (Dihydrochloride Trizin 5)",
    "Surgery Procedure (5000)": "Surgery Procedure (5000)",
    "Biopsy result": "Biopsy Result",
    "Chewies Immunolicious": "Chewies Immunolicious",
    "Ambroxol HCl (Tempracof)": "Ambroxol Hydrochloride (Tempracof)",
    "Vaxneuvance (PCV 15)": "PCV \"Vaxneuvance\" Vaccine",
    "Coamoxiclav 457 5mg": "Coamoxiclav 457 5mg",
    "MEDICAL ABSTRACT": "Medical Abstract",
    "Co-amoxiclav (Natravox)": "Co-amoxiclav (Natravox)",
    "Mebendazole": "Mebendazole",
    "Zinc Oxide + Calamine (Calmoseptine)": "Zinc Oxide and Calamine (Calmoseptine)",
    "Zinc Oxide +Calamine (Calmoseptine)": "Zinc Oxide and Calamine (Calmoseptine)",
    "Admin Fee - Doc Claveria": "Administration Fee",
    "Surgery Procedure (11500)": "Surgery Procedure (11500)"
}